"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const signupRoute_1 = require("../controllers/signupRoute");
const userRouter = (0, express_1.Router)();
userRouter.get("/", signupRoute_1.getUsers);
userRouter.post("/", signupRoute_1.registerUser);
userRouter.get("/:userId", signupRoute_1.getUserById);
userRouter.delete("/:userId", signupRoute_1.deleteUser);
exports.default = userRouter;
