"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const blogs_1 = require("../controllers/blogs");
const blogRouter = (0, express_1.Router)();
blogRouter.post("/", blogs_1.createBlog);
blogRouter.get("/", blogs_1.getBlogs);
blogRouter.get("/:blogId", blogs_1.getBlogById);
blogRouter.patch("/:blogId", blogs_1.updateBlog);
blogRouter.delete("/:blogId", blogs_1.deleteBlog);
exports.default = blogRouter;
